# Generated by Django 6.1 on 2026-09-03 16:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Real name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Age')),
                ('about', models.CharField(max_length=500, verbose_name='About')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
